### PR TITLE
Fix prefixing of functions

### LINKED ISSUE #145: Not working with imported built-in functions
```php
use function getcwd();
```

is going to be prefixed:

```php
use function PhpScoperXXX\getcwd();
```

which is obviously wrong

### PR DESCRIPTION
**Pull request by theofidry**
Now prefix functions whenever possible. A function is not prefixed when is an internal function or when the function fully qualified name could not be resolved.

Related to #152.
Closes #145.

The failure on the e2e tests is unrelated.

### CODE REVIEW

File: src/Reflector.php [hunk 1]
```diff
@@ -34,4 +39,16 @@ public function isClassInternal(string $name): bool
             return false;
         }
     }
+
+    public function isFunctionInternal(string $name): bool
+    {
+        try {
+            return (new ReflectionFunction($name))->isInternal();
+
+            // TODO: leverage Better Reflection instead
```
Comment (theofidry) [inline src/Reflector.php]: @Ocramius could you double check that? I may have misunderstood how it works but from what I see the identifier is correctly built but `PhpInternalSourceLocator` just tries to get the class from that identifier (which fails here as it's a function). 

See [source](https://github.com/Roave/BetterReflection/blob/master/src/SourceLocator/Type/PhpInternalSourceLocator.php#L42)

Comment (Ocramius) [reply src/Reflector.php]: Aye, that looks like a bug in BR

**Comment by theofidry** [comment]
I'll do the switch to BR when it will be fixed there then :) I reported the issue in https://github.com/Roave/BetterReflection/issues/407
