### PR TITLE
Fix string resolution with leading backslas

### LINKED ISSUE #356: `ReflectionClassConstant ` has been reported as non-internal
See https://github.com/bobthecow/psysh/issues/581#issuecomment-560137900

### PR DESCRIPTION
**Pull request by theofidry**
Closes #356

### CODE REVIEW

File: src/PhpParser/NodeVisitor/StringScalarPrefixer.php [hunk 1]
```diff
@@ -107,6 +108,8 @@ private function prefixStringScalar(String_ $string): String_
             return $string;
         }
 
+        $normalizedValue = '\\' === $string->value[0] ? substr($string->value, 1) : $string->value;
```
Comment (BackEndTea) [inline src/PhpParser/NodeVisitor/StringScalarPrefixer.php]: Wouldn't an `ltrim` be cleaner here?

Comment (BackEndTea) [reply src/PhpParser/NodeVisitor/StringScalarPrefixer.php]: e.g. `$normalizedValue  = ltrim($string->value, '\\');`

Comment (theofidry) [reply src/PhpParser/NodeVisitor/StringScalarPrefixer.php]: Indeed, much better
